import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const montser = Montserrat({
  variable: '--montser',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" id="start" className={`${montser.className} antialiased tracking-[0.03em] p-0`}>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
    </html>
  );
}
